### ISSUE TITLE
Application firmware version not compatible with python nlabapi

### ISSUE THREAD

**Issue by ndm736** [nLabs-nScope/nscope-rs#19]
nLab firmware is up to date for app v1.2.0

Running list_all_nscopes.py returns:

Link to nLab v2 [ REQUIRES FIRMWARE UPDATE ] [ available: true ]

Calling nlabapi = LabBench.open_first_available() returns:

RuntimeError: Cannot connect to any nLabs

Running update_firmware.rs changes the firmware, and then running list_all_nscopes.py returns:

Link to nLab v2 [ available: true ]

and the nlabapi function calls work as expected.

Then opening the app updates the firmware back to the original state that does not connect to the api

**Comment by davidjmeyer** [comment]
This was because the app hadn't been released with new firmware. That's been addressed with https://github.com/nLabs-nScope/nLab/releases/tag/1.2.1
